# Generated by Django 5.2.7 on 2026-02-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myfirstapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
